### PR TITLE
Improved responses

### PR DESCRIPTION
**Pull request by cindro**
Valid json responses which are now consistent in format and cleaner STKPushRequest.cs

### CODE REVIEW

**Comment by cindro** [comment]
There is no conflict btw, github thinks there is a conflict.

Ref: https://github.com/cindro/MpesaSDK.NET/blob/master/MpesaSDK.NET/Dtos/Requests/STKPushRequest.cs

**Comment by cindro** [comment]
If you happy with the code and accept the pull request, could you please release a nuget package, thank you.

**Review by mutiadavid — COMMENTED** [review]
Rename from Lipa to STKPush please.

**Comment by mutiadavid** [comment]
Pull my latest updates, check updated STKPushAsync and StkPushQueryAsync, for your changes you will just need to add STKPushResponse (LipaResponse) and StkPushQueryResponse(LipaResponse) then change methods return types and un-comment lines before return statement. You don't need to add other methods.

**Comment by cindro** [comment]
Even better....the code looks great and thank you for the new package release.

P.S.  StkPushResponse & StkPushQueryResponse were the logical names...hehehehe what was I thinking.

**Comment by mutiadavid** [comment]
Thanks for your contributions, Great job. Feel free to make changes to improve the SDK.

**Pull request merged**
